package in.handyman.raven.lib;

import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.model.DocnetAttribution;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "DocnetAttribution"
)
public class DocnetAttributionAction implements IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final DocnetAttribution docnetAttribution;

  private final Marker aMarker;

  public DocnetAttributionAction(final ActionExecutionAudit action, final Logger log,
      final Object docnetAttribution) {
    this.docnetAttribution = (DocnetAttribution) docnetAttribution;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker(" DocnetAttribution:"+this.docnetAttribution.getName());
  }

  @Override
  public void execute() throws Exception {
  }

  @Override
  public boolean executeIf() throws Exception {
    return docnetAttribution.getCondition();
  }
}
