package in.handyman.raven.lib;

import in.handyman.raven.core.context.ActionContext;
import in.handyman.raven.lambda.LambdaAutowire;
import in.handyman.raven.lambda.LambdaExecution;
import in.handyman.raven.lib.model.FbFormDownload;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import lombok.extern.log4j.Log4j2;
import org.apache.logging.log4j.MarkerManager;

/**
 * Auto Generated By Raven
 */
@LambdaAutowire(
    lambdaName = "FbFormDownload"
)
@Log4j2
public class FbFormDownloadAction implements LambdaExecution {
  private final ActionContext actionContext;

  private final FbFormDownload context;

  private final MarkerManager.Log4jMarker aMarker;

  public FbFormDownloadAction(final ActionContext actionContext, final Object context) {
    this.context = (FbFormDownload) context;
    this.actionContext = actionContext;
    this.aMarker = new MarkerManager.Log4jMarker("FbFormDownload");
    this.actionContext.getDetailMap().putPOJO("context", context);
  }

  @Override
  public void execute() throws Exception {
  }

  @Override
  public boolean executeIf() throws Exception {
    return false;
  }
}
