package in.handyman.raven.lib;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.jcraft.jsch.*;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.model.SftpConnector;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
        actionName = "SftpConnector"
)
public class SftpConnectorAction implements IActionExecution {
    private final ActionExecutionAudit action;

    private final Logger log;

    private final SftpConnector sftpConnector;

    private final Marker aMarker;

    private final ObjectMapper mapper = new ObjectMapper();

    public SftpConnectorAction(final ActionExecutionAudit action, final Logger log,
                               final Object sftpConnector) {
        this.sftpConnector = (SftpConnector) sftpConnector;
        this.action = action;
        this.log = log;
        this.aMarker = MarkerFactory.getMarker(" SftpConnector:" + this.sftpConnector.getName());
    }

    @Override
    public void execute() throws Exception {
        final String remoteHost = sftpConnector.getHost();
        final String userName = sftpConnector.getUserName();
        final String password = sftpConnector.getPassword();
        final int remotePort = Integer.parseInt(sftpConnector.getPort());
        final int sessionTimeout = Integer.parseInt(sftpConnector.getSessionTimeOut());
        final int channelTimeout = Integer.parseInt(sftpConnector.getChannelTimeOut());
        final String destDir = sftpConnector.getDestDir();
        final String remoteFile = sftpConnector.getSourceFile();
        log.info(aMarker, "Got the sftp details for the host {} and user {}", remoteHost, userName);
        Session jschSession = null;
        try {
            JSch jsch = new JSch();
            jsch.setKnownHosts("/home/sanjeeya.v@zucisystems.com/.ssh/known_hosts");
            jschSession = jsch.getSession(userName, remoteHost, remotePort);
            jschSession.setPassword(password);
            jschSession.connect(sessionTimeout);
            Channel sftp = jschSession.openChannel("sftp");
            sftp.connect(channelTimeout);
            log.info(aMarker, "sftp connection established for the host {} and user {}", remoteHost, userName);
            ChannelSftp channelSftp = (ChannelSftp) sftp;
            if (!(remoteFile.isEmpty())) {
                channelSftp.get(remoteFile, destDir);
                log.info(aMarker, "Downloaded {} file and saved in the {} directory", remoteFile, destDir);
                String name = "sftp-file-download-connector-response";
                action.getContext().put(name, mapper.readTree(destDir).toString());
                channelSftp.exit();
            }
        } catch (JSchException | SftpException e) {
            e.printStackTrace();
        } finally {
            if (jschSession != null) {
                jschSession.disconnect();
            }
        }
    }

    @Override
    public boolean executeIf() throws Exception {
        return sftpConnector.getCondition();
    }
}
