package in.handyman.raven.lib;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import in.handyman.raven.exception.HandymanException;
import in.handyman.raven.lambda.access.ResourceAccess;
import in.handyman.raven.lambda.action.ActionExecution;
import in.handyman.raven.lambda.action.IActionExecution;
import in.handyman.raven.lambda.doa.audit.ActionExecutionAudit;
import in.handyman.raven.lib.CoproProcessor;
import in.handyman.raven.lib.model.PaperItemizer;
import in.handyman.raven.lib.model.paperItemizer.PaperItemizerData;
import in.handyman.raven.lib.model.paperItemizer.PaperItemizerInputTable;
import in.handyman.raven.lib.model.paperItemizer.PaperItemizerOutputTable;
import in.handyman.raven.lib.model.paperItemizer.PaperItemizerResponse;
import in.handyman.raven.lib.model.triton.TritonInputRequest;
import in.handyman.raven.lib.model.triton.TritonRequest;
import okhttp3.*;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.argument.Arguments;
import org.jdbi.v3.core.argument.NullArgument;
import org.slf4j.Logger;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import static org.checkerframework.checker.units.UnitsTools.s;

/**
 * Auto Generated By Raven
 */
@ActionExecution(
    actionName = "PaperItemizer"
)
public class PaperItemizerAction implements IActionExecution {
  private final ActionExecutionAudit action;

  private final Logger log;

  private final PaperItemizer paperItemizer;

  private final Marker aMarker;

  public PaperItemizerAction(final ActionExecutionAudit action, final Logger log,
      final Object paperItemizer) {
    this.paperItemizer = (PaperItemizer) paperItemizer;
    this.action = action;
    this.log = log;
    this.aMarker = MarkerFactory.getMarker(" PaperItemizer:"+this.paperItemizer.getName());
  }

  @Override
  public void execute(){
    try {
      log.info(aMarker, "paper itemizer Action has been started {}",paperItemizer);

      final Jdbi jdbi = ResourceAccess.rdbmsJDBIConn(paperItemizer.getResourceConn());
      jdbi.getConfig(Arguments.class).setUntypedNullArgument(new NullArgument(Types.NULL));
      final String outputDir = Optional.ofNullable(paperItemizer.getOutputDir()).map(String::valueOf).orElse(null);
      log.info(aMarker, "paper itemizer Action output directory {}",outputDir);
      //5. build insert prepare statement with output table columns
      final String insertQuery = "INSERT INTO " +paperItemizer.getResultTable()+
              "(origin_id,group_id,tenant_id,template_id,processed_file_path,paper_no, status,stage,message,created_on,process_id,root_pipeline_id,model_name,model_version) " +
              " VALUES(?,?, ?,?, ?,?, ?,?,?,? ,?,  ?,?,?)";
      log.info(aMarker, "paper itemizer Insert query {}", insertQuery);

      //3. initiate copro processor and copro urls
      final List<URL> urls = Optional.ofNullable(action.getContext().get("copro.paper-itemizer.url")).map(s -> Arrays.stream(s.split(",")).map(s1 -> {
        try {
          return new URL(s1);
        } catch (MalformedURLException e) {
          log.error("Error in processing the URL ", e);
          throw new HandymanException("Error in processing the URL", e, action);
        }
      }).collect(Collectors.toList())).orElse(Collections.emptyList());
      log.info(aMarker, "paper itemizer copro urls {}", urls);

      final CoproProcessor<PaperItemizerInputTable, PaperItemizerOutputTable> coproProcessor =
              new CoproProcessor<>(new LinkedBlockingQueue<>(),
                      PaperItemizerOutputTable.class,
                      PaperItemizerInputTable.class,
                      jdbi, log,
                      new PaperItemizerInputTable(), urls, action);

      log.info(aMarker, "paper itemizer copro coproProcessor initialization  {}", coproProcessor);

      //4. call the method start producer from coproprocessor
      coproProcessor.startProducer(paperItemizer.getQuerySet(), Integer.valueOf(action.getContext().get("read.batch.size")));
      log.info(aMarker, "paper itemizer copro coproProcessor startProducer called read batch size {}",action.getContext().get("read.batch.size"));
      Thread.sleep(1000);
      coproProcessor.startConsumer(insertQuery, Integer.valueOf(action.getContext().get("paper.itemizer.consumer.API.count")), Integer.valueOf(action.getContext().get("write.batch.size")), new PaperItemizerConsumerProcess(log, aMarker,outputDir, action));
      log.info(aMarker, "paper itemizer copro coproProcessor startConsumer called consumer count {} write batch count {} ",Integer.valueOf(action.getContext().get("paper.itemizer.consumer.API.count")),Integer.valueOf(action.getContext().get("write.batch.size")));

    }catch(Exception ex){
      log.error(aMarker,"error in execute method for paper itemizer  ",ex);
      throw new HandymanException("error in execute method for paper itemizer", ex, action);
    }
  }

  public static class PaperItemizerConsumerProcess implements CoproProcessor.ConsumerProcess<PaperItemizerInputTable,PaperItemizerOutputTable>{

    private final Logger log;
    private final Marker aMarker;
    private final ObjectMapper mapper = new ObjectMapper();
    private static final MediaType MediaTypeJSON = MediaType
            .parse("application/json; charset=utf-8");
    private final String outputDir;

    public final ActionExecutionAudit action;
    final OkHttpClient httpclient = new OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.MINUTES)
            .writeTimeout(10, TimeUnit.MINUTES)
            .readTimeout(10, TimeUnit.MINUTES)
            .build();

    public PaperItemizerConsumerProcess(Logger log, Marker aMarker, String outputDir, ActionExecutionAudit action) {
      this.log = log;
      this.aMarker = aMarker;
      this.outputDir = outputDir;
      this.action = action;
    }

    @Override
    public List<PaperItemizerOutputTable> process(URL endpoint, PaperItemizerInputTable entity) throws Exception {
      log.info(aMarker,"coproProcessor consumer process started with endpoint {} and entity {}",endpoint,entity);
      List<PaperItemizerOutputTable> parentObj = new ArrayList<>();
      String inputFilePath = entity.getFilePath();
      Long rootPipelineId=entity.getRootPipelineId();
      final String paperItemizerProcessName = "PAPER_ITEMIZER";
      Long actionId=action.getActionId();
      ObjectMapper objectMapper = new ObjectMapper();
//payload
      PaperItemizerData paperitemizerData = new PaperItemizerData();
      paperitemizerData.setRootPipelineId(rootPipelineId);
      paperitemizerData.setProcess(paperItemizerProcessName);
      paperitemizerData.setInputFilePath(inputFilePath);
      paperitemizerData.setOutputDir(outputDir);
      paperitemizerData.setActionId(actionId);
      String jsonInputRequest = objectMapper.writeValueAsString(paperitemizerData);
      JsonNode jsonNodeRequest = objectMapper.readTree(jsonInputRequest);

      TritonRequest requestBody = new TritonRequest();
      requestBody.setName("PAPER_ITEMIZER");
      requestBody.setShape(List.of(1, 1));
      requestBody.setDatatype("BYTES");
     requestBody.setData(Collections.singletonList(jsonNodeRequest));

      TritonInputRequest tritonInputRequest=new TritonInputRequest();
      tritonInputRequest.setInputs(Collections.singletonList(requestBody));


      String jsonRequest = objectMapper.writeValueAsString(tritonInputRequest);

      log.info(aMarker,"coproProcessor mapper object node {}",jsonRequest);
      Request request = new Request.Builder().url(endpoint)
              .post(RequestBody.create(jsonRequest, MediaTypeJSON)).build();

      if(log.isInfoEnabled()) {
        log.info(aMarker, "Request has been build with the parameters \n URI : {}, with inputFilePath {} and outputDir {}", endpoint, inputFilePath, outputDir);
      }
      AtomicInteger atomicInteger = new AtomicInteger();
      String originId = entity.getOriginId();
      Integer groupId = entity.getGroupId();
      String templateId = entity.getTemplateId();
      String tenantId = entity.getTenantId();
      Long processId = entity.getProcessId();


      try(Response response=httpclient.newCall(request).execute()){

        if(log.isInfoEnabled()){
          log.info(aMarker,"coproProcessor consumer process response with status{}, and message as {}, ", response.isSuccessful(), response.message());}
        if (response.isSuccessful()) {
          String responseBody = response.body().string();
          ObjectMapper objectMappers = new ObjectMapper();
          PaperItemizerResponse paperItemizerResponse = objectMappers.readValue(responseBody, PaperItemizerResponse.class);
          if (paperItemizerResponse.getOutputs() != null && !paperItemizerResponse.getOutputs().isEmpty()) {
            paperItemizerResponse.getOutputs().forEach(o -> {
                o.getData().forEach(PaperItemizerDataItem -> {
                  parentObj.add(
                          PaperItemizerOutputTable
                                  .builder()
                                  .processedFilePath(String.valueOf(s))
                                  .originId(Optional.ofNullable(originId).map(String::valueOf).orElse(null))
                                  .groupId(groupId)
                                  .templateId(templateId)
                                  .tenantId(tenantId)
                                  .processId(processId)
                                  .paperNo(atomicInteger.incrementAndGet())
                                  .status("COMPLETED")
                                  .stage(paperItemizerProcessName)
                                  .message("Paper Itemizer macro completed")
                                  .createdOn(Timestamp.valueOf(LocalDateTime.now()))
                                  .rootPipelineId(rootPipelineId)
                                  .model_name(paperItemizerResponse.getModel_name())
                                  .model_version(paperItemizerResponse.getModel_version())
                                  .build());

                });
            });
           }

        }else{
          parentObj.add(
                  PaperItemizerOutputTable
                          .builder()
                          .originId(Optional.ofNullable(originId).map(String::valueOf).orElse(null))
                          .groupId(groupId)
                          .processId(processId)
                          .templateId(templateId)
                          .tenantId(tenantId)
                          .paperNo(atomicInteger.incrementAndGet())
                          .status("FAILED")
                          .stage(paperItemizerProcessName)
                          .message(response.message())
                          .createdOn(Timestamp.valueOf(LocalDateTime.now()))
                          .rootPipelineId(rootPipelineId)
                          .build());
          log.error(aMarker, "Error in response {}",response.message());
        }

      }catch (Exception exception) {
        parentObj.add(
                        PaperItemizerOutputTable
                        .builder()
                        .originId(Optional.ofNullable(originId).map(String::valueOf).orElse(null))
                        .groupId(groupId)
                        .processId(processId)
                        .templateId(templateId)
                        .tenantId(tenantId)
                        .paperNo(atomicInteger.incrementAndGet())
                        .status("FAILED")
                        .stage(paperItemizerProcessName)
                        .message(exception.getMessage())
                        .createdOn(Timestamp.valueOf(LocalDateTime.now()))
                        .rootPipelineId(rootPipelineId)
                        .build());
        HandymanException handymanException = new HandymanException(exception);
        HandymanException.insertException("Paper Itemizer  consumer failed for originId "+ originId, handymanException, this.action);
        log.error(aMarker, "The Exception occurred in request {}", request, exception);
      }
      atomicInteger.set(0);
      log.info(aMarker,"coproProcessor consumer process with output entity {}",parentObj);
      return parentObj;
    }
  }
  @Override
  public boolean executeIf() throws Exception {
    return paperItemizer.getCondition();
  }
  //1. input pojo from select query, which implements CoproProcessor.Entity

  //2. output pojo for table, which implements CoproProcessor.Entity

  }

