package in.handyman.raven.lib.model;

import in.handyman.raven.lambda.action.ActionContext;
import in.handyman.raven.lambda.action.IActionContext;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ActionContext(
        actionName = "Datevalidator"
)
public class Datevalidator implements IActionContext {
    private String name;

    private String thresholdValue;

    private String inputValue;

    private String allowedDateFormats;

    private String comparableDate;

    private Boolean condition = true;
}
