package in.handyman.raven.lib.model;

import in.handyman.raven.lambda.action.ActionContext;
import in.handyman.raven.lambda.action.IActionContext;
import java.lang.Boolean;
import java.lang.String;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ActionContext(
    actionName = "DonutImpiraQa"
)
public class DonutImpiraQa implements IActionContext {
  private String name;

  private String outputDir;

  private String resourceConn;

  private String responseAs;

  private String questionSql;

  private Boolean condition = true;

  private String forkBatchSize;
}
