package in.handyman.raven.lib.model;

import in.handyman.raven.lambda.action.ActionContext;
import in.handyman.raven.lambda.action.IActionContext;
import java.lang.Boolean;
import java.lang.String;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ActionContext(
    actionName = "EpisodeOfCoverage"
)
public class EpisodeOfCoverage implements IActionContext {
  private String name;

  private String resourceConn;

  private String originId;

  private String groupId;

  private String totalPages;

  private String outputTable;

  private String eocGroupingItem;

  private String eocIdCount;

  private String filepath;

  private String qrInput;

  private String value;

  private String pndValue;

  private Boolean condition = true;
}
