package in.handyman.raven.lib.model;

import in.handyman.raven.compiler.RavenParser;
import in.handyman.raven.lambda.action.ActionContext;
import in.handyman.raven.lambda.action.IActionContext;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@ActionContext(
        actionName = "Multitude"
)
public class Multitude implements IActionContext {
    private String name;

    private String on;

    private List<RavenParser.ActionContext> actions;

    private Boolean condition = true;

    private String writeThreadCount;
}
