/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Copydata</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.Copydata#getSource <em>Source</em>}</li>
 *   <li>{@link in.handyman.dsl.Copydata#getTo <em>To</em>}</li>
 *   <li>{@link in.handyman.dsl.Copydata#getFetchBatchSize <em>Fetch Batch Size</em>}</li>
 *   <li>{@link in.handyman.dsl.Copydata#getWriteBatchSize <em>Write Batch Size</em>}</li>
 *   <li>{@link in.handyman.dsl.Copydata#getValue <em>Value</em>}</li>
 *   <li>{@link in.handyman.dsl.Copydata#getWriteThreadCount <em>Write Thread Count</em>}</li>
 * </ul>
 *
 * @see in.handyman.dsl.DslPackage#getCopydata()
 * @model
 * @generated
 */
public interface Copydata extends Action
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see in.handyman.dsl.DslPackage#getCopydata_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Copydata#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see #setTo(String)
   * @see in.handyman.dsl.DslPackage#getCopydata_To()
   * @model
   * @generated
   */
  String getTo();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Copydata#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see #getTo()
   * @generated
   */
  void setTo(String value);

  /**
   * Returns the value of the '<em><b>Fetch Batch Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fetch Batch Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fetch Batch Size</em>' attribute.
   * @see #setFetchBatchSize(int)
   * @see in.handyman.dsl.DslPackage#getCopydata_FetchBatchSize()
   * @model
   * @generated
   */
  int getFetchBatchSize();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Copydata#getFetchBatchSize <em>Fetch Batch Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fetch Batch Size</em>' attribute.
   * @see #getFetchBatchSize()
   * @generated
   */
  void setFetchBatchSize(int value);

  /**
   * Returns the value of the '<em><b>Write Batch Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Write Batch Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write Batch Size</em>' attribute.
   * @see #setWriteBatchSize(int)
   * @see in.handyman.dsl.DslPackage#getCopydata_WriteBatchSize()
   * @model
   * @generated
   */
  int getWriteBatchSize();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Copydata#getWriteBatchSize <em>Write Batch Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write Batch Size</em>' attribute.
   * @see #getWriteBatchSize()
   * @generated
   */
  void setWriteBatchSize(int value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see in.handyman.dsl.DslPackage#getCopydata_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Copydata#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Write Thread Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Write Thread Count</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write Thread Count</em>' attribute.
   * @see #setWriteThreadCount(int)
   * @see in.handyman.dsl.DslPackage#getCopydata_WriteThreadCount()
   * @model
   * @generated
   */
  int getWriteThreadCount();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Copydata#getWriteThreadCount <em>Write Thread Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write Thread Count</em>' attribute.
   * @see #getWriteThreadCount()
   * @generated
   */
  void setWriteThreadCount(int value);

} // Copydata
