/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Es Accumulate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.EsAccumulate#getSource <em>Source</em>}</li>
 *   <li>{@link in.handyman.dsl.EsAccumulate#getTarget <em>Target</em>}</li>
 *   <li>{@link in.handyman.dsl.EsAccumulate#getFetchSize <em>Fetch Size</em>}</li>
 *   <li>{@link in.handyman.dsl.EsAccumulate#getWriteSize <em>Write Size</em>}</li>
 *   <li>{@link in.handyman.dsl.EsAccumulate#getValue <em>Value</em>}</li>
 *   <li>{@link in.handyman.dsl.EsAccumulate#getWriteThreadCount <em>Write Thread Count</em>}</li>
 * </ul>
 *
 * @see in.handyman.dsl.DslPackage#getEsAccumulate()
 * @model
 * @generated
 */
public interface EsAccumulate extends Action
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see in.handyman.dsl.DslPackage#getEsAccumulate_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link in.handyman.dsl.EsAccumulate#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see in.handyman.dsl.DslPackage#getEsAccumulate_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link in.handyman.dsl.EsAccumulate#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Fetch Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fetch Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fetch Size</em>' attribute.
   * @see #setFetchSize(String)
   * @see in.handyman.dsl.DslPackage#getEsAccumulate_FetchSize()
   * @model
   * @generated
   */
  String getFetchSize();

  /**
   * Sets the value of the '{@link in.handyman.dsl.EsAccumulate#getFetchSize <em>Fetch Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fetch Size</em>' attribute.
   * @see #getFetchSize()
   * @generated
   */
  void setFetchSize(String value);

  /**
   * Returns the value of the '<em><b>Write Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Write Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write Size</em>' attribute.
   * @see #setWriteSize(String)
   * @see in.handyman.dsl.DslPackage#getEsAccumulate_WriteSize()
   * @model
   * @generated
   */
  String getWriteSize();

  /**
   * Sets the value of the '{@link in.handyman.dsl.EsAccumulate#getWriteSize <em>Write Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write Size</em>' attribute.
   * @see #getWriteSize()
   * @generated
   */
  void setWriteSize(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see in.handyman.dsl.DslPackage#getEsAccumulate_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link in.handyman.dsl.EsAccumulate#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Write Thread Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Write Thread Count</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write Thread Count</em>' attribute.
   * @see #setWriteThreadCount(String)
   * @see in.handyman.dsl.DslPackage#getEsAccumulate_WriteThreadCount()
   * @model
   * @generated
   */
  String getWriteThreadCount();

  /**
   * Sets the value of the '{@link in.handyman.dsl.EsAccumulate#getWriteThreadCount <em>Write Thread Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write Thread Count</em>' attribute.
   * @see #getWriteThreadCount()
   * @generated
   */
  void setWriteThreadCount(String value);

} // EsAccumulate
