/**
 * generated by Xtext 2.25.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Load Csv</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.LoadCsv#getSource <em>Source</em>}</li>
 *   <li>{@link in.handyman.dsl.LoadCsv#getTo <em>To</em>}</li>
 *   <li>{@link in.handyman.dsl.LoadCsv#getDelim <em>Delim</em>}</li>
 *   <li>{@link in.handyman.dsl.LoadCsv#getFetchBatchSize <em>Fetch Batch Size</em>}</li>
 *   <li>{@link in.handyman.dsl.LoadCsv#getWriteBatchSize <em>Write Batch Size</em>}</li>
 *   <li>{@link in.handyman.dsl.LoadCsv#getValue <em>Value</em>}</li>
 *   <li>{@link in.handyman.dsl.LoadCsv#getWriteThreadCount <em>Write Thread Count</em>}</li>
 * </ul>
 *
 * @model
 * @generated
 * @see in.handyman.dsl.DslPackage#getLoadCsv()
 */
public interface LoadCsv extends Action {
    /**
     * Returns the value of the '<em><b>Source</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Source</em>' attribute.
     * @model
     * @generated
     * @see #setSource(String)
     * @see in.handyman.dsl.DslPackage#getLoadCsv_Source()
     */
    String getSource();

    /**
     * Sets the value of the '{@link in.handyman.dsl.LoadCsv#getSource <em>Source</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Source</em>' attribute.
     * @generated
     * @see #getSource()
     */
    void setSource(String value);

    /**
     * Returns the value of the '<em><b>To</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>To</em>' attribute.
     * @model
     * @generated
     * @see #setTo(String)
     * @see in.handyman.dsl.DslPackage#getLoadCsv_To()
     */
    String getTo();

    /**
     * Sets the value of the '{@link in.handyman.dsl.LoadCsv#getTo <em>To</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>To</em>' attribute.
     * @generated
     * @see #getTo()
     */
    void setTo(String value);

    /**
     * Returns the value of the '<em><b>Delim</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Delim</em>' attribute.
     * @model
     * @generated
     * @see #setDelim(String)
     * @see in.handyman.dsl.DslPackage#getLoadCsv_Delim()
     */
    String getDelim();

    /**
     * Sets the value of the '{@link in.handyman.dsl.LoadCsv#getDelim <em>Delim</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Delim</em>' attribute.
     * @generated
     * @see #getDelim()
     */
    void setDelim(String value);

    /**
     * Returns the value of the '<em><b>Fetch Batch Size</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Fetch Batch Size</em>' attribute.
     * @model
     * @generated
     * @see #setFetchBatchSize(int)
     * @see in.handyman.dsl.DslPackage#getLoadCsv_FetchBatchSize()
     */
    int getFetchBatchSize();

    /**
     * Sets the value of the '{@link in.handyman.dsl.LoadCsv#getFetchBatchSize <em>Fetch Batch Size</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Fetch Batch Size</em>' attribute.
     * @generated
     * @see #getFetchBatchSize()
     */
    void setFetchBatchSize(int value);

    /**
     * Returns the value of the '<em><b>Write Batch Size</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Write Batch Size</em>' attribute.
     * @model
     * @generated
     * @see #setWriteBatchSize(int)
     * @see in.handyman.dsl.DslPackage#getLoadCsv_WriteBatchSize()
     */
    int getWriteBatchSize();

    /**
     * Sets the value of the '{@link in.handyman.dsl.LoadCsv#getWriteBatchSize <em>Write Batch Size</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Write Batch Size</em>' attribute.
     * @generated
     * @see #getWriteBatchSize()
     */
    void setWriteBatchSize(int value);

    /**
     * Returns the value of the '<em><b>Value</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Value</em>' attribute.
     * @model
     * @generated
     * @see #setValue(String)
     * @see in.handyman.dsl.DslPackage#getLoadCsv_Value()
     */
    String getValue();

    /**
     * Sets the value of the '{@link in.handyman.dsl.LoadCsv#getValue <em>Value</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Value</em>' attribute.
     * @generated
     * @see #getValue()
     */
    void setValue(String value);

    /**
     * Returns the value of the '<em><b>Write Thread Count</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Write Thread Count</em>' attribute.
     * @model
     * @generated
     * @see #setWriteThreadCount(int)
     * @see in.handyman.dsl.DslPackage#getLoadCsv_WriteThreadCount()
     */
    int getWriteThreadCount();

    /**
     * Sets the value of the '{@link in.handyman.dsl.LoadCsv#getWriteThreadCount <em>Write Thread Count</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Write Thread Count</em>' attribute.
     * @generated
     * @see #getWriteThreadCount()
     */
    void setWriteThreadCount(int value);

} // LoadCsv
