/**
 * generated by Xtext 2.25.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Send Mail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.SendMail#getPrivateKey <em>Private Key</em>}</li>
 *   <li>{@link in.handyman.dsl.SendMail#getImpersonatedUser <em>Impersonated User</em>}</li>
 *   <li>{@link in.handyman.dsl.SendMail#getDbSrc <em>Db Src</em>}</li>
 *   <li>{@link in.handyman.dsl.SendMail#getValue <em>Value</em>}</li>
 *   <li>{@link in.handyman.dsl.SendMail#getDryrunMail <em>Dryrun Mail</em>}</li>
 * </ul>
 *
 * @model
 * @generated
 * @see in.handyman.dsl.DslPackage#getSendMail()
 */
public interface SendMail extends Action {
    /**
     * Returns the value of the '<em><b>Private Key</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Private Key</em>' attribute.
     * @model
     * @generated
     * @see #setPrivateKey(String)
     * @see in.handyman.dsl.DslPackage#getSendMail_PrivateKey()
     */
    String getPrivateKey();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SendMail#getPrivateKey <em>Private Key</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Private Key</em>' attribute.
     * @generated
     * @see #getPrivateKey()
     */
    void setPrivateKey(String value);

    /**
     * Returns the value of the '<em><b>Impersonated User</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Impersonated User</em>' attribute.
     * @model
     * @generated
     * @see #setImpersonatedUser(String)
     * @see in.handyman.dsl.DslPackage#getSendMail_ImpersonatedUser()
     */
    String getImpersonatedUser();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SendMail#getImpersonatedUser <em>Impersonated User</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Impersonated User</em>' attribute.
     * @generated
     * @see #getImpersonatedUser()
     */
    void setImpersonatedUser(String value);

    /**
     * Returns the value of the '<em><b>Db Src</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Db Src</em>' attribute.
     * @model
     * @generated
     * @see #setDbSrc(String)
     * @see in.handyman.dsl.DslPackage#getSendMail_DbSrc()
     */
    String getDbSrc();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SendMail#getDbSrc <em>Db Src</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Db Src</em>' attribute.
     * @generated
     * @see #getDbSrc()
     */
    void setDbSrc(String value);

    /**
     * Returns the value of the '<em><b>Value</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Value</em>' attribute.
     * @model
     * @generated
     * @see #setValue(String)
     * @see in.handyman.dsl.DslPackage#getSendMail_Value()
     */
    String getValue();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SendMail#getValue <em>Value</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Value</em>' attribute.
     * @generated
     * @see #getValue()
     */
    void setValue(String value);

    /**
     * Returns the value of the '<em><b>Dryrun Mail</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Dryrun Mail</em>' attribute.
     * @model
     * @generated
     * @see #setDryrunMail(String)
     * @see in.handyman.dsl.DslPackage#getSendMail_DryrunMail()
     */
    String getDryrunMail();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SendMail#getDryrunMail <em>Dryrun Mail</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Dryrun Mail</em>' attribute.
     * @generated
     * @see #getDryrunMail()
     */
    void setDryrunMail(String value);

} // SendMail
