/**
 * generated by Xtext 2.25.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sms Lead Sms</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.SmsLeadSms#getUrl <em>Url</em>}</li>
 *   <li>{@link in.handyman.dsl.SmsLeadSms#getSender <em>Sender</em>}</li>
 *   <li>{@link in.handyman.dsl.SmsLeadSms#getAccount <em>Account</em>}</li>
 *   <li>{@link in.handyman.dsl.SmsLeadSms#getPrivateKey <em>Private Key</em>}</li>
 *   <li>{@link in.handyman.dsl.SmsLeadSms#getDbSrc <em>Db Src</em>}</li>
 *   <li>{@link in.handyman.dsl.SmsLeadSms#getValue <em>Value</em>}</li>
 *   <li>{@link in.handyman.dsl.SmsLeadSms#getDryrunNumber <em>Dryrun Number</em>}</li>
 * </ul>
 *
 * @model
 * @generated
 * @see in.handyman.dsl.DslPackage#getSmsLeadSms()
 */
public interface SmsLeadSms extends Action {
    /**
     * Returns the value of the '<em><b>Url</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Url</em>' attribute.
     * @model
     * @generated
     * @see #setUrl(String)
     * @see in.handyman.dsl.DslPackage#getSmsLeadSms_Url()
     */
    String getUrl();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SmsLeadSms#getUrl <em>Url</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Url</em>' attribute.
     * @generated
     * @see #getUrl()
     */
    void setUrl(String value);

    /**
     * Returns the value of the '<em><b>Sender</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Sender</em>' attribute.
     * @model
     * @generated
     * @see #setSender(String)
     * @see in.handyman.dsl.DslPackage#getSmsLeadSms_Sender()
     */
    String getSender();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SmsLeadSms#getSender <em>Sender</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Sender</em>' attribute.
     * @generated
     * @see #getSender()
     */
    void setSender(String value);

    /**
     * Returns the value of the '<em><b>Account</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Account</em>' attribute.
     * @model
     * @generated
     * @see #setAccount(String)
     * @see in.handyman.dsl.DslPackage#getSmsLeadSms_Account()
     */
    String getAccount();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SmsLeadSms#getAccount <em>Account</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Account</em>' attribute.
     * @generated
     * @see #getAccount()
     */
    void setAccount(String value);

    /**
     * Returns the value of the '<em><b>Private Key</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Private Key</em>' attribute.
     * @model
     * @generated
     * @see #setPrivateKey(String)
     * @see in.handyman.dsl.DslPackage#getSmsLeadSms_PrivateKey()
     */
    String getPrivateKey();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SmsLeadSms#getPrivateKey <em>Private Key</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Private Key</em>' attribute.
     * @generated
     * @see #getPrivateKey()
     */
    void setPrivateKey(String value);

    /**
     * Returns the value of the '<em><b>Db Src</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Db Src</em>' attribute.
     * @model
     * @generated
     * @see #setDbSrc(String)
     * @see in.handyman.dsl.DslPackage#getSmsLeadSms_DbSrc()
     */
    String getDbSrc();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SmsLeadSms#getDbSrc <em>Db Src</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Db Src</em>' attribute.
     * @generated
     * @see #getDbSrc()
     */
    void setDbSrc(String value);

    /**
     * Returns the value of the '<em><b>Value</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Value</em>' attribute.
     * @model
     * @generated
     * @see #setValue(String)
     * @see in.handyman.dsl.DslPackage#getSmsLeadSms_Value()
     */
    String getValue();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SmsLeadSms#getValue <em>Value</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Value</em>' attribute.
     * @generated
     * @see #getValue()
     */
    void setValue(String value);

    /**
     * Returns the value of the '<em><b>Dryrun Number</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @return the value of the '<em>Dryrun Number</em>' attribute.
     * @model
     * @generated
     * @see #setDryrunNumber(String)
     * @see in.handyman.dsl.DslPackage#getSmsLeadSms_DryrunNumber()
     */
    String getDryrunNumber();

    /**
     * Sets the value of the '{@link in.handyman.dsl.SmsLeadSms#getDryrunNumber <em>Dryrun Number</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @param value the new value of the '<em>Dryrun Number</em>' attribute.
     * @generated
     * @see #getDryrunNumber()
     */
    void setDryrunNumber(String value);

} // SmsLeadSms
