/**
 * generated by Xtext 2.16.0
 */
package in.handyman.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import in.handyman.DslRuntimeModule;
import in.handyman.DslStandaloneSetup;
import in.handyman.ide.DslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DslIdeSetup extends DslStandaloneSetup {
  @Override
  public Injector createInjector() {
    DslRuntimeModule _dslRuntimeModule = new DslRuntimeModule();
    DslIdeModule _dslIdeModule = new DslIdeModule();
    return Guice.createInjector(Modules2.mixin(_dslRuntimeModule, _dslIdeModule));
  }
}
