/**
 * generated by Xtext 2.16.0
 */
package in.handyman.ide;

import in.handyman.ide.AbstractDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
