/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dogleg</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.Dogleg#getInheritContext <em>Inherit Context</em>}</li>
 *   <li>{@link in.handyman.dsl.Dogleg#getProcessList <em>Process List</em>}</li>
 * </ul>
 *
 * @see in.handyman.dsl.DslPackage#getDogleg()
 * @model
 * @generated
 */
public interface Dogleg extends Action
{
  /**
   * Returns the value of the '<em><b>Inherit Context</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inherit Context</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inherit Context</em>' attribute.
   * @see #setInheritContext(String)
   * @see in.handyman.dsl.DslPackage#getDogleg_InheritContext()
   * @model
   * @generated
   */
  String getInheritContext();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Dogleg#getInheritContext <em>Inherit Context</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inherit Context</em>' attribute.
   * @see #getInheritContext()
   * @generated
   */
  void setInheritContext(String value);

  /**
   * Returns the value of the '<em><b>Process List</b></em>' containment reference list.
   * The list contents are of type {@link in.handyman.dsl.StartProcess}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Process List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process List</em>' containment reference list.
   * @see in.handyman.dsl.DslPackage#getDogleg_ProcessList()
   * @model containment="true"
   * @generated
   */
  EList<StartProcess> getProcessList();

} // Dogleg
