package in.handyman.raven.lib.model;

import in.handyman.raven.lambda.action.ActionContext;
import in.handyman.raven.lambda.action.IActionContext;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ActionContext(
        actionName = "DocnetAttribution"
)
public class DocnetAttribution implements IActionContext {
    private String name;

    private String inputFilePath;

    private String questionList;

    private String absentKeyFilterList;

    private String outputDir;


    private Boolean condition = true;
}
