package in.handyman.raven.lib.model;

import in.handyman.raven.lambda.Lambda;
import in.handyman.raven.lambda.LambdaContext;
import java.lang.Boolean;
import java.lang.String;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@LambdaContext(
    lambdaName = "FbFormDownload"
)
public class FbFormDownload implements Lambda {
  private String name;

  private String accessToken;

  private String appSecret;

  private String accountId;

  private String formId;

  private String target;

  private String value;

  private Boolean condition;
}
