package in.handyman.raven.lib.model;

import in.handyman.raven.lambda.action.ActionContext;
import in.handyman.raven.lambda.action.IActionContext;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ActionContext(
        actionName = "FtpsConnector"
)
public class FtpsConnector implements IActionContext {
    private String name;

    private String host;

    private String port;

    private String userName;

    private String password;

    private String sessionTimeOut;

    private String sourceFile;

    private String fileaction;

    private String destDir;

    private Boolean condition = true;
}
