package in.handyman.raven.lib.model;

import in.handyman.raven.lambda.Lambda;
import in.handyman.raven.lambda.LambdaContext;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Auto Generated By Raven
 */
@Data
@EqualsAndHashCode
@NoArgsConstructor
@LambdaContext(
    lambdaName = "Transform"
)
public class Transform implements Lambda {
  private String name;

  private String on;

  private String STRING;

  private List<String> value;

  private Boolean condition = true;
}
